# Generated by Django 5.1.2 on 2024-11-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_event_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
