# Generated by Django 5.1.2 on 2024-11-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0004_delete_event"),
        ("management", "0003_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Nome da área.", max_length=100)),
                ("size", models.FloatField(help_text="Tamanho da área em m².")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notas adicionais sobre esta área."
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_areas",
                        to="management.storage",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_areas",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
    ]
