# Generated by Django 5.1.2 on 2024-11-13 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0002_auto_20241009_2230"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título da tarefa, como Plantar ou Colher",
                        max_length=100,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("Planting", "Plantio"),
                            ("Harvesting", "Colheita"),
                            ("Watering", "Irrigação"),
                            ("Pruning", "Poda"),
                            ("Soil Management", "Remanejo do Solo"),
                        ],
                        help_text="Tipo de tarefa para a cultura.",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição ou notas adicionais sobre a tarefa.",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Data e hora de início do evento."),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Data e hora de término do evento."),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Baixa"),
                            ("Medium", "Média"),
                            ("High", "Alta"),
                        ],
                        default="Medium",
                        help_text="Prioridade da tarefa.",
                        max_length=20,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Indica se a tarefa foi concluída."
                    ),
                ),
                (
                    "weather_summary",
                    models.CharField(
                        blank=True,
                        help_text="Resumo das condições meteorológicas.",
                        max_length=255,
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        blank=True, help_text="Recomendação da IA baseada no clima."
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="crops.culturas",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-start_date"],
            },
        ),
    ]
