# Generated by Django 5.1.2 on 2024-11-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do item (semente, fertilizante, etc.).",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Seed", "Semente"),
                            ("Fertilizer", "Fertilizante"),
                            ("Pesticide", "Pesticida"),
                        ],
                        help_text="Categoria do item.",
                        max_length=50,
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Custo médio por unidade.",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unidade de medida (kg, litros, etc.).", max_length=50
                    ),
                ),
                (
                    "recommended_area",
                    models.FloatField(
                        help_text="Área recomendada para uso deste item (em m²)."
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="recommendation",
        ),
    ]
