# Generated by Django 5.1.2 on 2024-11-26 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0003_culturas_loss_percentage_culturas_yield_per_unit_and_more"),
        ("management", "0002_cropsuggestion_remove_event_recommendation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(help_text="Nome do produto.", max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Seed", "Semente"),
                            ("Fertilizer", "Fertilizante"),
                            ("Pesticide", "Pesticida"),
                        ],
                        help_text="Categoria do produto.",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(help_text="Quantidade do produto em estoque."),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unidade de medida (kg, litros, etc.).", max_length=50
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Custo médio por unidade.",
                        max_digits=10,
                    ),
                ),
                (
                    "recommended_area",
                    models.FloatField(
                        blank=True,
                        help_text="Área recomendada para uso deste produto (em m²).",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Data da última atualização."
                    ),
                ),
                (
                    "culture",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cultura associada a este armazenamento (se aplicável).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crops.culturas",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário que possui este armazenamento.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
