# Generated by Django 5.1.2 on 2024-10-09 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Culturas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da cultura, como tomate, alface, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("vegetable", "Vegetal"),
                            ("fruit", "Fruta"),
                            ("grain", "Grão"),
                            ("herb", "Erva"),
                            ("flower", "Flor"),
                        ],
                        help_text="Tipo de cultura (vegetal, fruta, grão, erva, flor).",
                        max_length=20,
                    ),
                ),
                (
                    "planting_season",
                    models.CharField(
                        help_text="Estação do ano ideal para o plantio, como primavera ou verão.",
                        max_length=100,
                    ),
                ),
                (
                    "harvest_season",
                    models.CharField(
                        help_text="Estação do ano em que a cultura deve ser colhida.",
                        max_length=100,
                    ),
                ),
                (
                    "growing_conditions",
                    models.TextField(
                        help_text="Condições necessárias para o crescimento da cultura, como solo, luz e irrigação."
                    ),
                ),
                (
                    "compatible_plants",
                    models.TextField(
                        help_text="Plantas que são compatíveis para o cultivo conjunto."
                    ),
                ),
                (
                    "common_pests",
                    models.TextField(
                        help_text="Pragas comuns que podem afetar esta cultura."
                    ),
                ),
                (
                    "watering_needs",
                    models.CharField(
                        help_text='Necessidades de irrigação da cultura, como "regular" ou "moderada".',
                        max_length=100,
                    ),
                ),
                (
                    "sun_exposure",
                    models.CharField(
                        help_text='Exposição ao sol necessária, como "sol pleno" ou "sombra parcial".',
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notas adicionais sobre a cultura."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cultura",
                "verbose_name_plural": "Culturas",
            },
        ),
    ]
